name: Publish

on:
  push:
    branches: main

jobs:
  publish:
    name: Publish container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # GHCR doesn't allow uppercase in package names
      - name: Downcase repo name
        run: |
          echo "repo_lower=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "ghcr.io/${{ env.repo_lower }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
